### ISSUE TITLE
bids validator hates dir-AP, but happy with acq-AP

### ISSUE THREAD

**Issue by dkp** [ReproNim/reproin#29]
Hi All, 
I tried generating a dataset for our Siemens Skyra here at the UA.  reproin mostly worked quite well.  However, the bids validator was not happy with files named using dir: sub-001_dir-AP_dwi.nii.gz, but was fine with sub-001_acq-AP_dwi.nii.gz.  Perhaps I misunderstood but I thought reproin suggested using the "dir" tag.  Thoughts?

**Comment by yarikoptic** [comment]
probably just that bids-validator didn't catch up yet with the changes to the BIDS standard (attn @chrisfilo).  We added _dir to DWI only recently in Nov https://github.com/bids-standard/bids-specification/pull/78 and it became a part of the BIDS 1.1.2 which was only a month ago.  As a temporary workaround you could setup configuration file for the bids-validator and specify those files to be ignored, see https://github.com/bids-standard/bids-validator#configuration .
Since nothing to be done on reproin side (you are welcome to chime in on bids-validator issues so adding support of _dir was not forgotten if it is not yet implemented in master), I am closing this one

**Comment by chrisfilo** [comment]
https://github.com/bids-standard/bids-validator/pull/694

**Comment by chrisfilo** [comment]
Doing the same for switching would be an easy and welcome PR to bids-validator.
