### ISSUE TITLE
Question Regarding Sequence Names

### ISSUE THREAD

**Issue by dlevitas** [ReproNim/reproin#35]
Hello,

Our imaging center is beginning to convert all our study DICOMS into BIDS format, and we are planning to use the ReproIn/heurdiconv workflows to accomplish this. I've been going over the provided walkthrough and source code, but have two lingering questions I wanted to clarify.

1). Our scanner collects three localizer DICOMS at the beginning of each protocol; can "localizer" be the seqtype label? In the code I see an option "_ses-localizer"; however, we're not planning on specifying session, so can a localizer scan just be listed as "localizer"?

2). Our sequence names normally have additional information appended at the end (i.e. _mb4_870vols or _MPRANGE_0.8mm). It seems like this information could be included in the _custom label; however, is it better to not include this in the sequence names, since this information is in the metadata anyway?

Thanks for the assistance.

Dan

**Comment by yarikoptic** [comment]
1) "scouts" (which I guess the localizers are) aren't covered by BIDS AFAIK. in reproin heuristic  [we do not convert them into BIDS, but do retain their dicoms under sourcedata/](https://github.com/nipy/heudiconv/blob/master/heudiconv/heuristics/reproin.py#L630), see e.g. http://datasets.datalad.org/?dir=/dbic/QA/sourcedata/sub-qa/ses-20180910/anat

`_ses-*` is completely optional and just used to describe session where needed.  We call them `anat-scout`. `localizer` is not defined in ReproIn. But if you already have them, we can figure out a workaround

2) up to you to decide.  When ppl really want those to be present, we just list them within `_acq-` field

**Comment by dlevitas** [comment]
Thanks @yarikoptic for your response. To clarify:

1). As far as I'm aware, we have two separate localizer protocols: ```AAHead_Scout``` and a normal localizer, which have different names in our system. It seems that the Scout localizers could simply be named ```anat-scout```; however, would this also be appropriate for the other localizer protocol? We currently haven't collected any data with the new sequence names, but I'm trying to make sure the names can be recognized by the reproin heuristic. 

2). I'll have to see what our MRI physicist thinks about this, but for now we'll plan to keep the sequence names short (i.e. not use the optional labels) for now. If however we choose to add more information to the sequence names, would something like ```anat-T1w_acq-MPRANGE-0.8mm``` or ```func_task-nback_run-01_acq-mb4-2mm``` be acceptable?

**Comment by yarikoptic** [comment]
1).  If that localizer of some value to keep in BIDS (is it full volume? what contrast (T1, T2w)?), I would just call it accordingly with disambiguation in `_acq`, e.g. anat-T1w_acq-localizer. 

2). unfortunately `-` and `.` are not yet a part of BIDS.  I have filed now [an issue](https://github.com/bids-standard/bids-specification/issues/226) about `-` since I could not find one (although we did have discussions about it in some form).  `.` is trickier one since would mess with file extensions.  In ReproIn convention you could definitely have the `-` but [we will replace them](https://github.com/nipy/heudiconv/blob/master/heudiconv/heuristics/reproin.py#L890) with big `X` to stay compliant with BIDS.  May be we should do the same to `.`?

**Comment by satra** [comment]
@dlevitas - it may be useful to check how dcm2nii converts the 3 slice localizer. technically i think it will need 3 nifti files. since each orthogonal plane will require a separate qform. 

i think it has a single series UID but generates multiple files when converted.

the aascout is different since that doesn't have multiple orientations.

on the naming front in our center - we use reproin with any center specific semantics going after `__`

**Comment by dlevitas** [comment]
The localizer does not have any BIDS value; sorry for not specifying that. I've normally use dcmbids/dcm2niix for BIDS conversion in the past, and with that 3 separate nifti files are created for the localizer, which are then discarded and not put into the BIDS folders. Since this specific localizer doesn't have any value, is it just okay then to leave its name as ```localizer``` or does it need a heuristic that the program can recognize?

Ah okay, I didn't realize ```.``` and ```-``` weren't proper BIDS format. For now, I'll stick with underscore, and I noticed in the source code that ```0.6mm``` can be expressed as ```060mm``` I believe. Regardless, we'll leave that peripheral information out of the sequence names for the time being.

**Comment by yarikoptic** [comment]
1) of you name it anat-scout_acq-localizer I think it will also be ignored as a scout
2) _ is used by bids to separate entities, don't use it to separate within value!

**Comment by dlevitas** [comment]
1). okay, we'll go with the ```anat-scout_acq-localizer``` for our scouts/localizers 
2). Got it, thanks for clarifying.

I think that answers the lingering questions I had. I'll close this out now. Thanks again, @yarikoptic @satra
